version: '3'

services:
  react:
    build:
      #current directory
      context: .
      # use file
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    #volumes:
    #  - /app/node_modules
    #  - .:/app
