FROM node:alpine

WORKDIR /app

COPY ./package.json .
RUN npm config set unsafe-perm true
RUN npm install --force
# RUN npm install

COPY . .

RUN apk -U add vim

RUN chown -R node /app/node_modules
USER node

CMD ["npm", "start"]
